### PR TITLE
A few script cleanups and fixes

### PR DESCRIPTION
**Pull request by lethal-guitar**
Hi @Exarkuniv, thanks again for creating & sharing your build script! I've made a few changes and minor fixes in this PR. One of the changes is to use a specific release version (0.8.2 at the moment) instead of the `master` branch. This way, using the script gives you a stable and well-tested version. But the downside is that the script needs to be updated every time I make a new release. But I'm happy to take care of that myself and make a PR whenever I publish a new release.

I've removed and reinstalled the game on my Pi 3 using the updated script, and the build worked without problems.

I was also wondering if you'd be open to contributing this to the upstream repo (https://github.com/RetroPie/RetroPie-Setup)? RigelEngine would be available as a package for all RetroPie users then. I'd be happy to help with that process - I haven't contributed to the RetroPie repo yet but I can be available to answer questions the maintainers might have and help with making changes should they request any.

Let me know what you think! And once again, really appreciate that you made this repo - thank you! 🎉 👍🏻

### CODE REVIEW

**Comment by Exarkuniv** [comment]
Im still very new to how Git hub works and whatnot. lol took me some time on how to figure it all out

**Comment by lethal-guitar** [comment]
Np 🙂

**Comment by Exarkuniv** [comment]
i have submitted a PR for the RetorPie-Master. so we will see. it would be cool to have it added. about time i contributed to it. lol

**Comment by lethal-guitar** [comment]
Nice!

**Pull request merged**
